In [2]:
import tensorflow as tf
tf.__version__

'2.16.1'

In [3]:
a = tf.constant([[1.,2.,3.],[11.,12.,13.]])
a

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  2.,  3.],
       [11., 12., 13.]], dtype=float32)>

In [4]:
a.shape

TensorShape([2, 3])

In [12]:
a.dtype

tf.float32

## Basic Mathematics

In [11]:
a+a

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [22., 24., 26.]], dtype=float32)>

In [7]:
a*a

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[  1.,   4.,   9.],
       [121., 144., 169.]], dtype=float32)>

In [8]:
a/a

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [10]:
a%a

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [14]:
a*3

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 3.,  6.,  9.],
       [33., 36., 39.]], dtype=float32)>

## Example 1

In [16]:
import tensorflow as tf
import tensorflow_datasets as tfds

# Construct a tf.data.Dataset
ds = tfds.load('mnist', split='train', shuffle_files=True)

# Build your input pipeline
ds = ds.shuffle(1024).batch(32).prefetch(tf.data.AUTOTUNE)
for example in ds.take(1):
  image, label = example["image"], example["label"]

ModuleNotFoundError: No module named 'tensorflow_datasets'

In [17]:
import tensorflow_datasets as tfds
mnist_data = tfds.load("mnist")
mnist_train, mnist_test = mnist_data["train"], mnist_data["test"]
assert isinstance(mnist_train, tf.data.Dataset)

ModuleNotFoundError: No module named 'tensorflow_datasets'